# This module provide an easy way to print out all the tracks

import os, pandas as pd

def get_track(search, metadata, online_path, local_path='./', suffix='.bw'):
    """
    :param: search: csv file generated by ChIPseqpair search
    :param: metadata: csv file generated by ChIPseqpair query
    :param online_path: the path for UCSC genome browser
    :param local_path: the path that store the bigwig file
    :return: print out the track url
    """
    files = [x for x in os.listdir(local_path) if x.endswith(suffix)]

    online_path += '/' if not online_path.endswith('/') else ''

    search_df = pd.read_csv(search, index_col=0)
    metadata_df = pd.read_csv(metadata, sep='\t', index_col=0)

    human_tracks = []
    mouse_tracks = []
    for f in files:
        track_cmd = 'track '
        if suffix =='.bw':
            track_cmd += 'type=bigWig '

        name = f[:f.find('.')]
        track_cmd += 'name="'+ name+'" '

        track_cmd += 'description="" visibility=2 '

        if f.startswith('ENC'):
            species = search_df.ix[name, 'Organism']
        elif f.startswith('SRR'):
            species = search_df.ix[metadata_df.ix[name, 'GSM_ID'], 'Organism']

        if species == 'Homo sapiens':
            track_cmd += 'db=hg19 '
        if species == 'Mus musculus':
            track_cmd += 'db=mm9 '

        track_cmd += 'color=0,0,255 maxHeightPixels=30:30:30 windowingFunction=maximum viewLimits=0:500 autoScale=auto bigDataUrl=http://cigwiki.houstonmethodist.org/trackhub/boxia/' + online_path + f

        if species == 'Homo sapiens':
            human_tracks.append(track_cmd)
        if species == 'Mus musculus':
            mouse_tracks.append(track_cmd)

    for t in human_tracks:
        print t

    print

    for t in mouse_tracks:
        print t


def get_track_own(online_path, local_path='./', suffix='.bw',mouse_tracks=True, human_tracks=False):
    """
    :param: search: csv file generated by ChIPseqpair search
    :param: metadata: csv file generated by ChIPseqpair query
    :param online_path: the path for UCSC genome browser
    :param local_path: the path that store the bigwig file
    :return: print out the track url
    """
    files = [x for x in os.listdir(local_path) if x.endswith(suffix)]

    online_path += '/' if not online_path.endswith('/') else ''

    humans = []
    mouse = []

    for f in files:
        track_cmd = 'track '
        if suffix =='.bw':
            track_cmd += 'type=bigWig '

        name = f[:f.find('.')]
        track_cmd += 'name="'+ name+'" '

        track_cmd += 'description="" visibility=2 '

        if human_tracks:
            track_cmd += 'db=hg19 '
        if mouse_tracks:
            track_cmd += 'db=mm9 '

        track_cmd += 'color=0,0,255 maxHeightPixels=60:60:60 windowingFunction=maximum autoScale=auto viewLimits=0:50 bigDataUrl=http://cigwiki.houstonmethodist.org/trackhub/boxia/' + online_path + f

        if human_tracks:
            humans.append(track_cmd)
        if mouse_tracks:
            mouse.append(track_cmd)

    for t in humans:
        print t

    print

    for t in sorted(mouse):
        print t


get_track_own('Erin/Chip-seq/')
